### ISSUE TITLE
图片没有变化

### ISSUE THREAD

**Issue by holycharles** [xwxtwd/wepy-plugin-img2base64#3]
图片还是没有转成base64不知道是哪的问题

**Comment by xwxtwd** [comment]
@holycharles 这东西是临时兼容我的项目，图片路径没有做自动识别，没转成base64应该是路径问题，可以在配置path: './{图片路径}',没转换成功可以看看日志，程序跑到那里找图片了

实在没空弄这个，不好意思了

**Comment by fantasy525** [comment]
什么时候可以转换css中的图片为base64?
